create table reader(
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       reader_ticket_number int UNIQUE GENERATED ALWAYS AS (id) STORED,
                       full_name varchar(100) NOT NULL ,
                       date_of_birth DATE NOT NULL CHECK (date_of_birth < CURRENT_DATE),
                       email varchar(100) NOT NULL UNIQUE,
                       created_at timestamp,
                       updated_at timestamp
);

create table book
(
    id   integer generated by default as identity primary key,
    reader_id integer references reader on delete cascade ,
    title     varchar(200),
    author    varchar(200),
    year      integer ,
    taken_at  timestamp,
    added_at timestamp
);

